create table dashboard (id bigint generated by default as identity (start with 1), locked boolean not null, type integer, version integer, primary key (id));
create table dashboard_widget (id bigint generated by default as identity (start with 1), version integer,collapsed boolean, position integer, widget_id bigint, primary key (id));
create table dashboard_widgets (dashboard_id bigint not null, widgets_id bigint not null, primary key (dashboard_id, widgets_id));
create table widget (id bigint generated by default as identity (start with 1), version integer, height integer not null, name varchar(255), title varchar(255), view_name varchar(255), width integer not null, primary key (id));

alter table dashboard_widgets add constraint UK_f4a8dt0xifkry6agj2idjdcp4  unique (widgets_id);
alter table dashboard_widget add constraint FK_bgea0vdj4sfvry99aukcambgn foreign key (widget_id) references widget;
alter table dashboard_widgets add constraint FK_f4a8dt0xifkry6agj2idjdcp4 foreign key (widgets_id) references dashboard_widget;
alter table dashboard_widgets add constraint FK_dc8ynfayd7ow93aj3uggub2db foreign key (dashboard_id) references dashboard;
