package com.globant.agilepodmaster.sync.datamodel;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import lombok.Data;

@Data
public class ReleaseData implements Serializable {
  
  private int number;

  private String name;

  private float progress;

  private boolean autoGenerated;

  private String tag;

  private List<TaskData> backlog;

  private List<SprintData> sprints;

  private List<RiskData> risks;

  private List<HighlightData> highlights;

  public ReleaseData(final String name, final boolean autoGenerated) {
    this.name = name;
    this.autoGenerated = autoGenerated;
    backlog = new ArrayList<TaskData>();
    sprints = new ArrayList<SprintData>();
    risks = new ArrayList<RiskData>();
    highlights = new ArrayList<HighlightData>();
  }
  
  
  
}
