package com.globant.agilepodmaster.sync.datamodel;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import lombok.Data;

@Data
public class ReleaseData implements Serializable {
  
  public int number;

  public String name;

  public float progress;

  public boolean autoGenerated;

  public String tag;

  public List<TaskData> backlog;

  public List<SprintData> sprints;

  public List<RiskData> risks;

  public List<HighlightData> highlights;

  public ReleaseData(final String name, final boolean autoGenerated) {
    this.name = name;
    this.autoGenerated = autoGenerated;
    backlog = new ArrayList<TaskData>();
    sprints = new ArrayList<SprintData>();
    risks = new ArrayList<RiskData>();
    highlights = new ArrayList<HighlightData>();
  }
  
  
  
}
