package com.globant.agilepodmaster.sync.datamodel;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import lombok.Data;

/**
 * DTO that represents a release taken from a data source.
 * 
 * @author jose.dominguez@globant.com
 *
 */
@Data
public class ReleaseData implements Serializable {
  
  private int number;

  private String name;

  private float progress;

  private boolean autoGenerated;

  private String tag;

  private List<TaskData> backlog;

  private List<SprintData> sprints;

  private List<RiskData> risks;

  private List<HighlightData> highlights;

  /**
   * Constructor.
   * 
   * @param name the name of the release.
   * @param autoGenerated true if it was created by the process, otherwise if
   *        was taken form the data source.
   */
  public ReleaseData(final String name, final boolean autoGenerated) {
    this.autoGenerated = autoGenerated; 
    this.name = name;
    backlog = new ArrayList<TaskData>();
    sprints = new ArrayList<SprintData>();
    risks = new ArrayList<RiskData>();
    highlights = new ArrayList<HighlightData>();
  }
  
  
  
}
